### ISSUE TITLE
Should "NONE" and "NOASSERTION" be valid licenses?

### ISSUE THREAD

**Issue by jandrieu** [kemitchell/spdx.js#11]
I just added this issue over at npm : https://github.com/npm/npm/issues/8557 , but it isn't clear to me if the logic for "NONE" and "NOASSERTION" should be handled by spdx clients (like npm) or if it should be treated as valid when calling spdx.valid("NONE") and spex.valid("NOASSERTION").

See http://spdx.org/sites/spdx/files/SPDX-2.0.pdf section Section 3.12-3.14. "NONE" and "NOASSERTION" are valid values for Concluded Licenses (3.12), All Licenses Information From Files (3.13), and Declared Licenses (3.14).  However, they are not described as "<SPDX LIcense Expression> is a valid SPDX License Expression as defined in Appendix IV."

Which means it isn't quite clear if valid() should treat "NONE" and "NOASSERTION" as valid SPDX License Expressions and return true.

However, it seems clear from the spec that "NONE" and "NOASSERTION" are valid fields wherever a valid SPDX License Expression is allowed.

So... is this a feature request/bug in SPDX? Where we should update it here to return true for spdx.valid("NONE") and spex.valid("NOASSERTION") or if users of the SPDX module should be aware that "NONE" and "NOASSERTION" are allowed in the spec, but not "valid" per Appendix IV, and therefore should be handled as special cases. 

In the latter case, my issue at npm would be the right place to fix it. Otherwise it would be here.

Any suggestions about the right place to work on this use case?

**Comment by jandrieu** [comment]
FWIW, I added an issue at spdx.org asking for clarification about the validity of "NONE" and "NOASSERTION": https://bugs.linuxfoundation.org/show_bug.cgi?id=1289

**Comment by kemitchell** [comment]
Thank your for this issue! I was traveling today, but will make time to get back to you this weekend.

**Comment by mburtoniii** [comment]
A license expression is a type that represents the licensing terms of a piece of software (e.g., source file, binary). An SPDX document is a simple database of licensing information. The SPDX fields are analogous to database fields. Database fields could accept different types (Integer, Float, Date, XML, …) or they could have special field values like NULL (= missing or unknown data). NONE and NOASSERTION do not represent licensing terms but instead describes a state of analysis. NONE and NOASSERTION are valid SPDX field values but they are not valid license expressions (they do not represent the licensing terms of a piece of software). Similarly, NULL does not represent a valid Date value in an SQL data base, but instead is a valid field value that describes the state of assignment (Just as much as NULL is not a valid integer). 
It would be more semantically correct to discuss what are valid values for a for a given SPDX field. In the case of “LicenseConcluded” that would be:
    <SPDX License Expression> | “NONE” | “NOASSERTION”

**Comment by kemitchell** [comment]
@mburtoniii, thank you for your comment! Might you be so kind as to have a look at my comment on the npm issue, https://github.com/npm/npm/issues/8557#issuecomment-111783659, and comment there if our views on `NONE` and `NOASSERTION` differ?

**Comment by kemitchell** [comment]
Closing, but please feel free to reach out with additional questions or comments.
