### ISSUE TITLE
Function to get list of licenses mentioned in expression

### ISSUE THREAD

**Issue by gamtiq** [kemitchell/spdx.js#12]
It would be useful to have a function that returns list of licenses that are mentioned in given SPDX expression.
For example:

``` js
spdx.list('MIT');   // => ['MIT']
spdx.list('Invalid-Identifier');   // => []
spdx.list('(LGPL-2.1 AND MIT AND BSD-2-Clause)');   // => ['LGPL-2.1', 'MIT', 'BSD-2-Clause']
spdx.list('(LGPL-2.1+ OR BSD-3-Clause AND MIT)'); );   // => ['LGPL-2.1', 'BSD-3-Clause', 'MIT']
```

**Comment by kemitchell** [comment]
Sure! Might you be interested in writing that package? I'd probably use `spdx.parse` and a bit of recursion.

I am of a mind to split spdx.js into more modules in the near future. At a minimum, I think `satisfies` should be split off.

**Comment by gamtiq** [comment]
I am interested to write such function or package. But unfortunately I will be able to do it only in 3 or 4 weeks, not earlier.

**Comment by kemitchell** [comment]
Closing the issue, but please feel free to stay in touch!
