### ISSUE TITLE
satisfies(license, expression) is missing in 0.4.2

### ISSUE THREAD

**Issue by aleung** [kemitchell/spdx.js#16]
It breaks application which depends on function `satisfies(license, expression)` after update to 0.4.2.

**Comment by kemitchell** [comment]
You're right! My mistake. I did a quick push to add a license file for the Fedora folks that swept up some functional changes.

Here is the tentative plan:
1. Deprecate 0.4.2
2. Cherry pick the addition of a copy of the MIT license to a new 0.4.3
3. Release the functional changes as new 0.5.0.

**Comment by kemitchell** [comment]
On a related note: May I ask how you are using the package? You may be interested in the more recent https://www.npmjs.com/package/spdx-satisfies. This package is maintained only because it's used in npm 2.x.

**Comment by kemitchell** [comment]
0.4.2 has been deprecated. 0.4.3, which is 0.4.1 with the addition of a copy of the MIT License, has been released. @aleung please let me know if this closes this issue. Sorry for the trouble.

**Comment by aleung** [comment]
@kemitchell  I'm not the maintainer of myndzi/node-license-validator, just found this issue when I installed it. I might make a pull request to him. This issue can be closed. Thank you.
