### ISSUE TITLE
Range Bugs

### ISSUE THREAD

**Issue by phadej** [kemitchell/spdx.js#9]
there are two ranges for`LPPL`, should there be one? https://github.com/kemitchell/spdx.js/blob/7186b8f92f0aa3c8f087e73b5f98bd1c776a4d3f/source/ranges.json#L111

``` js
  [
    "LPPL-1.0",
    "LPPL-1.1",
    "LPPL-1.2",
    "LPPL-1.3a",
    "LPPL-1.3c"
  ],
```

---

There aren't `AGPL` range, shouldn't there be `["AGPL-1.0", "AGPL-3.0"]`

---

There is `OPL` in `OSL` list https://github.com/kemitchell/spdx.js/blob/7186b8f92f0aa3c8f087e73b5f98bd1c776a4d3f/source/ranges.json#L159

is this a mistake?

---

The `MPL-1.0, MPL-1.1, MPL-2.0-no-copyleft-exception` is very suspicious license range.

https://github.com/kemitchell/spdx.js/blob/7186b8f92f0aa3c8f087e73b5f98bd1c776a4d3f/source/ranges.json#L128

**Comment by kemitchell** [comment]
I will PR fixes for LPPL-1.0+ and OSL-1.0+ very shortly.

I am not so sure about AGPL-1.0+.

As for MPL, there are actually two ranges, one with `-no-copyleft-exception` and one without. This ensures that both `gt(MPL-2.0-no-copyleft-exception, MPL-1.0` and `gt(MPL-2.0, MPL-1.0)`.

**Comment by phadej** [comment]
The http://en.wikipedia.org/wiki/Affero_General_Public_License says quite clearly that they are versions of the _same_ license. 

`MPL` issue is tricky. I don't really know how to interpret `MPL-1.0+` expression. Is it `MPL-1.0 OR MPL-1.1 OR MPL-2.0 OR MPL-no-copyleft-exception)` or without `no-copyleft-exception`or without `MPL-2.0`.

**Comment by kemitchell** [comment]
Thanks for another great comment!

Do we have a better source for the AGPL relationship? I'd like to close that out in #10, as well.

MPL is strange for a number of reasons. They seem to have approved a specific ID for a license with an exception.

**Comment by phadej** [comment]
http://www.affero.org/oagpl.html is that enough?

> Additionally, in order to permit "upgrading" existing software released under the Affero General Public License version 1 or later as published by Affero, Inc. to GNU AGPLv3, Affero has published the Affero General Public License version 2.

**Comment by kemitchell** [comment]
Ahoy! I forgot about that clause. Thanks very much!

**Comment by kemitchell** [comment]
@phadej, I think #10 addresses all of the issues you found, apart from MPL. I'd like to close this issue and open a separate one for the MPL range. Please go ahead and open one if you'd like to lead it. Otherwise I'll do so this weekend.
